Handling insight tx/send errors
produces pretty and understandable exceptions, such as:

ValueError: Transaction rejected by network (code -26). Reason: 64: non-canonical

Conflicts:

	pycoin/services/insight.py